# Generated by Django 3.0.4 on 2020-05-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejecteduser',
            name='rejectedUserID',
        ),
    ]
