# Generated by Django 3.0.4 on 2020-05-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rejecteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepteduser',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
