# Generated by Django 3.0.3 on 2020-04-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_userswaitingresponse_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
