# Generated by Django 3.0.4 on 2020-05-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_accepteduser_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepteduser',
            name='init_rep',
            field=models.BooleanField(default=False),
        ),
    ]
