# Generated by Django 3.0.3 on 2020-04-26 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0004_rejectedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_OU', models.BooleanField(default=True)),
                ('is_VIP', models.BooleanField(default=False)),
                ('is_SU', models.BooleanField(default=False)),
                ('rep_score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='firstName', max_length=50)),
                ('lastName', models.CharField(default='lastName', max_length=50)),
                ('email', models.EmailField(default='email@email.com', max_length=254)),
                ('interest', models.TextField(default='My interest are')),
                ('credential', models.TextField(default='My credentials are')),
                ('reference', models.CharField(default='Name', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userswaitingresponse',
            name='response',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
