# Generated by Django 3.0.3 on 2020-04-27 00:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0005_auto_20200426_2356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcceptedUsers',
            new_name='AcceptedUser',
        ),
        migrations.RenameModel(
            old_name='RejectedUsers',
            new_name='RejectedUser',
        ),
    ]
