# Generated by Django 3.0.3 on 2020-05-02 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200427_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userswaitingresponse',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Application'),
        ),
    ]
