# Generated by Django 3.0.5 on 2020-05-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('guiltyUser', models.CharField(max_length=100, null=True)),
                ('guiltyGroup', models.CharField(max_length=100, null=True)),
                ('Reason', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='compliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('praises', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.AcceptedUser')),
            ],
        ),
    ]
