# Generated by Django 3.0.4 on 2020-05-11 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_rejectedinvitemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('priase', 'priase'), ('warn', 'warn'), ('kick', 'kick')], default='priase', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_count', models.IntegerField(default=0)),
                ('no_count', models.IntegerField(default=0)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Voting.VoteType')),
            ],
        ),
    ]
