# Generated by Django 3.0.4 on 2020-05-13 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votetype',
            name='vote_type',
            field=models.CharField(choices=[('priase', 'priase'), ('warn', 'warn'), ('kick', 'kick'), ('shutdown', 'shutdown')], default='priase', max_length=10),
        ),
        migrations.CreateModel(
            name='ClosedGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Groups.Group')),
            ],
        ),
    ]
