# Generated by Django 3.0.4 on 2020-05-08 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesu',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='votesu',
            name='vote_for',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
