# Generated by Django 3.0.4 on 2020-05-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0002_auto_20200512_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedgroups',
            name='isEvaluted',
            field=models.BooleanField(default=False),
        ),
    ]
