# Generated by Django 3.0.4 on 2020-05-09 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Voting', '0002_auto_20200508_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesu',
            name='voters',
            field=models.ManyToManyField(related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votesu',
            name='vote_for',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
