# Generated by Django 3.0.4 on 2020-05-10 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedInviteMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='Groups.Group')),
                ('invite_rejected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_rejected_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
