# Generated by Django 3.0.4 on 2020-05-05 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='count_members',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='members',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
