# Generated by Django 3.0.5 on 2020-05-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='groupName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
