# Generated by Django 3.0.4 on 2020-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0002_evaluationrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrep',
            name='blackBox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluationrep',
            name='reason',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='evaluationrep',
            name='whiteBox',
            field=models.BooleanField(default=False),
        ),
    ]
