# Generated by Django 3.0.4 on 2020-05-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0003_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
